# Generated by Django 4.2.1 on 2023-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_citizen_telephone_num_alter_citizen_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('Unknown', 'unknown'), ('Accept', 'accept'), ('Refuse', 'refuse'), ('Onhold', 'onhold')], default='Unknown'),
        ),
    ]
