# Generated by Django 4.2.1 on 2023-06-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_stage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='stage',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='clients.stage'),
        ),
    ]
